// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0615ca5e-c289-4cbe-b8a3-936e0ac81ec8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAccelerationChange();
void onAccidentStatChange();

CloudAcceleration acceleration;
float alcoholLevel;
CloudLocation liveLocation;
bool accidentStat;
bool bikeStat;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(acceleration, READWRITE, 1 * SECONDS, onAccelerationChange);
  ArduinoCloud.addProperty(alcoholLevel, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(liveLocation, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(accidentStat, READWRITE, ON_CHANGE, onAccidentStatChange);
  ArduinoCloud.addProperty(bikeStat, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
